# Basic
edition = "2021"
max_width = 100
use_small_heuristics = "Max"

# Imports
imports_granularity = "Crate"
reorder_imports = true

# Consistency
newline_style = "Unix"

# Misc
chain_width = 80
spaces_around_ranges = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true

# Format comments
comment_width = 100
wrap_comments = true
